add build arg and build context args
Stratoscale/skipper pull request #167
Opened 2023-12-26 06:35 UTC by khizunov

2023-12-26 13:10 UTC, ofir-amir reviewed
The bundling of lint fixes and other fixes make it hard to read

2023-12-26 13:10 UTC, ofir-amir commented on README.md
> +# Remember to commit if you changing the build container
```suggestion
# Remember to commit if you are changing the build container
```

2023-12-26 13:39 UTC, khizunov commented
> The bundling of lint fixes and other fixes make it hard to read

Guilty, forgot to disable auto-format.

2023-12-27 09:01 UTC, ofir-amir requested changes

2023-12-27 09:01 UTC, ofir-amir commented on skipper.yaml
> +build-container-image: skipper-build
any reason for removal of the new line?

2023-12-27 09:01 UTC, ofir-amir commented on skipper/cli.py
> +            main_context or os.path.dirname(dockerfile),
I would move line 116 to 120 and join the condition from 122.
Don't think that the optimization is that important

2023-12-27 09:01 UTC, ofir-amir commented on skipper/cli.py
> +    build_container = _prepare_build_container(
pass ctx.obj to _prepare_build_container? you are using it in multiple places

2023-12-27 09:01 UTC, ofir-amir commented on tests/test_cli.py
I this test config from skipper.yaml only or also from CLI or you expect to be handled by click?

2023-12-27 11:13 UTC, khizunov commented on skipper/cli.py
> +    build_container = _prepare_build_container(
IMO `_prepare_build_container` shouldn't be aware of ctx.

2023-12-27 12:43 UTC, khizunov commented on tests/test_cli.py
@ofir-amir this test is testing builder functionality.

2023-12-27 14:47 UTC, ofir-amir commented on tests/test_cli.py
oops - the question was on [tests/test_config.py](https://github.com/Stratoscale/skipper/pull/167/files#diff-da24b355349b53e4c8047034767d008e4c2ce9ea6c8933a3acd50d0828f00528)

2023-12-27 14:51 UTC, khizunov commented on tests/test_cli.py
these tests are only for config file. CLI verified by test_cli

2023-12-28 07:31 UTC, ofir-amir approved these changes

2023-12-30 13:28 UTC, merged